baseURL = 'https://blog.schemar.net/'
languageCode = 'en-us'
title = "schemar's blog"
theme = "PaperMod"
[params]
  [params.homeInfoParams]
    title = "schemar's blog"
    content = "A blog which couldn't be updated less frequently."
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/schemar"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/martinschenck/"
  [[params.socialIcons]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/2610345/schemar"
[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
